import { scoreAll } from './scoring.js';
import { applyDownDistance } from './downDistance.js';
import { normalizeSituation, coverageSituation } from './context.js';
import { rankCoveragesForSituation } from './coverageRank.js';
import { buildCallOptions } from './callOptions.js';
import { evaluateCoverage } from './playMatchup.js';
import { PLAYS } from '../data/plays.js';
import { getPlayAssignmentEvidence } from '../data/playEvidence.js';
import { isDeepSafeCall } from '../data/coverageFlags.js';
import { TRAIT_LABELS } from '../data/traits.js';
import { PERSONNEL_FAMILIES } from '../data/personnel.js';
import { normalizeUserProfile, userProfileLabels } from '../data/userProfile.js';

// The single entry point for live cards, details, sharing and PDF rows.
export function recommend({ traits = [], book = 'All', runPass = 4, familyId = null, down = 'base', distance = '', userProfile = {} } = {}) {
  const normalizedUserProfile = normalizeUserProfile(userProfile);
  const context = normalizeSituation(down, distance);
  const sit = coverageSituation(context);
  const scored = applyDownDistance(scoreAll(traits, book, runPass, familyId), down, distance);
  const formations = scored.flatMap(f => {
    // There is no clock/lead objective in this first phase: do not prescribe
    // Prevent from a red-zone or two-minute label alone. It stays in Reference.
    if (f.personnel === 'Prevent') return [];
    const plays = PLAYS[f.name] || [];
    const verified = f.coverages.filter(c => plays.some(p => p.n === c.name));
    const eligible = sit === '3lg'
      ? verified.filter(c => isDeepSafeCall(c.name))
      : verified;
    if (!eligible.length) return [];
    const baseline = rankCoveragesForSituation({ ...f, coverages: eligible }, sit, f.effectiveTraits);
    const rankedCoverages = baseline.map((c, index) => {
      const evidence = getPlayAssignmentEvidence(f.name, c.name);
      const evaluated = evaluateCoverage(c, plays.find(p => p.n === c.name), f.effectiveTraits, f.sc, evidence);
      return evaluated && { ...evaluated, baselineOrder: index };
    }).filter(c => c && c.sc > 0).sort((a, b) => b.sc - a.sc || a.baselineOrder - b.baselineOrder);
    if (!rankedCoverages.length) return [];
    const best = rankedCoverages[0];
    const callOptions = buildCallOptions(rankedCoverages, f.effectiveTraits, sit, 4, normalizedUserProfile);
    const playerCall = callOptions.find(call => call.isPlayerChoice) || callOptions[0];
    return [{ ...f, formationScore: f.sc, sc: best.sc, ledger: [...f.ledger, ...best.ledger],
      matchup: best.matchup, rankedCoverages, callOptions, recommendedCoverage: best.name,
      personalizedCoverage: playerCall?.name || best.name,
      personalizedReason: playerCall?.playerChoiceReason || '',
      inventoryOmissions: f.coverages.length - verified.length }];
  });
  formations.sort((a, b) => b.sc - a.sc || a.name.localeCompare(b.name));
  return { context, familyId, familyLabel: PERSONNEL_FAMILIES[familyId]?.label || 'All scouted looks', book, runPass,
    userProfile: normalizedUserProfile, userProfileLabels: userProfileLabels(normalizedUserProfile), formations };
}

export function buildRecommendationShareText(result, traits = []) {
  const lines = ['CFB 27 — DEFENSIVE GAME PLAN', `${result.familyLabel} · ${result.context.label} · ${result.book}`, ''];
  if (traits.length) lines.push('Scouted: ' + traits.map(t => TRAIT_LABELS[t] || t).join(', '), '');
  for (const [i, f] of result.formations.slice(0, 4).entries()) {
    lines.push(`#${i + 1} ${f.name} — fit ${f.sc}/100`, `My call: ${f.personalizedCoverage}`);
    if (f.personalizedCoverage !== f.recommendedCoverage) lines.push(`Best overall: ${f.recommendedCoverage}`);
    lines.push(`Assignments: ${f.matchup.structure}`);
    if (f.matchup.status === 'verified') lines.push(`Main concern: ${f.matchup.weaknesses[0] || 'No verified assignment warning triggered.'}`);
    lines.push(`Not assessed: ${f.matchup.unknowns.join(' ')}`);
    if (f.matchup.concept) lines.push(`Threat assessment: ${f.matchup.concept.utility}/100 (${f.matchup.concept.confidence.toLowerCase()} confidence)`,
      `Bad-case scenario: ${f.matchup.concept.badCase.label} — ${f.matchup.concept.mainConcession}`);
    lines.push(...f.ledger.filter(x => x.delta !== 0).map(x => `  ${x.label}: ${x.delta > 0 ? '+' : ''}${x.delta}`), '');
  }
  lines.push('Fit scores are heuristic rankings, not success probabilities.', 'Generated by Scheme Builders');
  return lines.join('\n');
}
