import { scoreAll } from './scoring.js';
import { applyDownDistance } from './downDistance.js';
import { normalizeSituation, coverageSituation } from './context.js';
import { rankCoveragesForSituation } from './coverageRank.js';
import { PLAYS } from '../data/plays.js';
import { TRAIT_LABELS } from '../data/traits.js';
import { PERSONNEL_FAMILIES } from '../data/personnel.js';

// The single entry point for live cards, details, sharing and PDF rows.
export function recommend({ traits = [], book = 'All', runPass = 4, familyId = null, down = 'base', distance = '' } = {}) {
  const context = normalizeSituation(down, distance);
  const sit = coverageSituation(context);
  const scored = applyDownDistance(scoreAll(traits, book, runPass, familyId), down, distance);
  const formations = scored.flatMap(f => {
    // There is no clock/lead objective in this first phase: do not prescribe
    // Prevent from a red-zone or two-minute label alone. It stays in Reference.
    if (f.personnel === 'Prevent') return [];
    const plays = PLAYS[f.name] || [];
    const verified = f.coverages.filter(c => plays.some(p => p.n === c.name));
    const eligible = sit === '3lg'
      ? verified.filter(c => plays.find(p => p.n === c.name).deep > 0)
      : verified;
    if (!eligible.length) return [];
    const rankedCoverages = rankCoveragesForSituation({ ...f, coverages: eligible }, sit, f.effectiveTraits);
    return [{ ...f, rankedCoverages, recommendedCoverage: rankedCoverages[0].name,
      inventoryOmissions: f.coverages.length - verified.length }];
  });
  return { context, familyId, familyLabel: PERSONNEL_FAMILIES[familyId]?.label || 'All scouted looks', book, runPass, formations };
}

export function buildRecommendationShareText(result, traits = []) {
  const lines = ['CFB 27 — DEFENSIVE GAME PLAN', `${result.familyLabel} · ${result.context.label} · ${result.book}`, ''];
  if (traits.length) lines.push('Scouted: ' + traits.map(t => TRAIT_LABELS[t] || t).join(', '), '');
  for (const [i, f] of result.formations.slice(0, 4).entries()) {
    lines.push(`#${i + 1} ${f.name} — fit ${f.sc}/100`, `Call: ${f.recommendedCoverage}`, `Suggested blitz frequency: ${f.blitz}%`);
    lines.push(...f.ledger.filter(x => x.delta !== 0).map(x => `  ${x.label}: ${x.delta > 0 ? '+' : ''}${x.delta}`), '');
  }
  lines.push('Fit scores are heuristic rankings, not success probabilities.', 'Generated by Scheme Builders');
  return lines.join('\n');
}
